# Generated by Django 4.1 on 2022-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_musician_instrument_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='musician',
        ),
        migrations.AddField(
            model_name='instrument',
            name='musician',
            field=models.ManyToManyField(related_name='instruments', to='api.musician'),
        ),
    ]
